# https://github.com/denolib/setup-deno
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.4.4
      - name: Run Tests
        run: |
          deno --version
          deno test -A
      - name: Setup CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: typescript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
