# https://github.com/denolib/setup-deno
name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Set up repository
        uses: actions/checkout@v2
      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.16.3
      - name: Perform Deno test
        run: |
          deno --version
          deno test -A
      - name: Set up CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: typescript
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v1
